// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oycckglbqjqtzpaufcql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95Y2NrZ2xicWpxdHpwYXVmY3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzQ2MTMsImV4cCI6MjA4ODU1MDYxM30.Ua_nwTLc3muT-Bq36-f6ZuTh2O1lTXzoKBZnB-zgpjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});